### PR TITLE
Add `create_file` step and  improve docs

### PR DESCRIPTION
**Pull request by d3sch41n**
WIP 

* this step is needed for a variety of use cases 
* new docs will focus more clearly on what first time visitors need to know

### CODE REVIEW

**Comment by l50** [comment]
Hey! Do you have examples of TTPs that need this functionality? I think it's a good idea, just want to understand the context behind this work.

**Comment by d3sch41n** [comment]
> Hey! Do you have examples of TTPs that need this functionality? I think it's a good idea, just want to understand the context behind this work.

Pressing need is from internal use cases. However, stuff like "write a malicious script into a repo", "write a new file in `/etc/sudoers.d", etc also qualifies - without this new step, you need to do `cat <<EOF` shenanigans that compromises the fidelity of the attack simulation (real attacker creating a file directly from their C2 implant won't make weird shell history/process execution logs)

**Comment by d3sch41n** [comment]
Progress update: added documentation and detailed examples for cleanup. 

Work in progress: adding documentation for command line argument processing and corresponding arguments.

**Comment by d3sch41n** [comment]
Actually since I decided I'm going to go hard on the docs, I'm going to break this + the upcoming docs functionality into multiple PRs - will update in a bit

**Comment by d3sch41n** [comment]
Closing - breaking out create_file, docs will go to armory

**Pull request closed without merging**
